name: PowerShell tests
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Windows PowerShell 5.1
        shell: powershell
        run: .\tests\Run-Tests.ps1
      - name: Test PowerShell 7
        if: ${{ !cancelled() }}
        shell: pwsh
        run: .\tests\Run-Tests.ps1
